// amp-burger-react/src/components/ingredients/Pickles.jsx
const Pickles = ({ amount }) => {
  return Array.from({ length: amount }, (v, i) => (
    <div style={styles.container} key={i}>
      <div style={styles.pickle} />
      <div style={styles.pickle} />
      <div style={styles.pickle} />
    </div>
  ));
};

const styles = {
  container: {
    display: "flex",
    flexDirection: "row",
    gap: 10,
  },
  pickle: {
    width: 60,
    height: 7,
    backgroundColor: "#69995D",
  },
};

export default Pickles;

// amp-burger-vue/src/components/ingredients/Pickles.vue
<template>
  <div class="pickleContainer" v-for="n in amount" :key="n">
    <div class="pickle" />
    <div class="pickle" />
    <div class="pickle" />
  </div>
</template>

<script>
export default {
  name: 'Pickles',
  props: {
    amount: {
      default: 0,
    },
  },
};
</script>

<style scoped>
.pickleContainer {
  display: flex;
  flex-direction: row;
  gap: 10px;
}
.pickle {
  background-color: #69995d;
  width: 60px;
  height: 7px;
}
</style>
