// amp-burger-vue/src/containers/BurgerBuilder.vue
<template>
  <div class="container">
    <h1>Welcome to amp burgerz 👋</h1>
    <!---
    <p>{{ summary }}</p>
    ---->
    <BurgerBuilderControls
      :isVeggie="isVeggie"
      @toggleVeggie="toggleVeggie"
      @addIngredient="addIngredient"
    />

    <EditableBurger
      :isVeggie="isVeggie"
      :ingredients="ingredients"
      @removeIngredient="removeIngredient"
    />
  </div>
</template>

<script>
import BurgerBuilderControls from '../components/BurgerBuilderControls.vue';
import EditableBurger from '../components/EditableBurger.vue';
// import summary from '../mixins/summary';
// import useSummary from '../compositions/useSummary';

export default {
  name: 'BurgerBuilder',
  components: {
    BurgerBuilderControls,
    EditableBurger,
  },
  //  mixins: [summary],
  data() {
    return {
      isVeggie: true,
      ingredients: {
        tomatos: 0,
        cheese: 0,
        patty: 0,
        pickles: 0,
      },
    };
  },
  methods: {
    toggleVeggie() {
      this.isVeggie = !this.isVeggie;
    },
    addIngredient(key) {
      this.ingredients[key] += 1;
    },
    removeIngredient(key) {
      if (this.ingredients[key] > 0) {
        this.ingredients[key] -= 1;
      }
      return true;
    },
  },

  // computed: {
  //   summary() {
  //     let totalAmount = 0;
  //     Object.values(this.ingredients).forEach((amount) => {
  //       totalAmount += amount;
  //     });
  //     if (totalAmount > 0) {
  //       return `Your burger has ${totalAmount} ingredients 🤤`;
  //     }
  //     return 'Your burger is empty 😢';
  //   },
  //
  //   summary() {
  //     const { summary } = useSummary({ ingredients: this.ingredients });
  //     return summary.value;
  //   },
  // },
};
</script>

<style scoped>
.container {
  padding-top: 20px;
  width: 100%;
  display: flex;
  align-items: center;
  flex-direction: column;
}
</style>

// amp-burger-react/src/containers/BurgerBuilder.jsx
import logo from './../logo.svg';
import { useState, useEffect } from 'react';
import BurgerBuilderControls from '../components/BurgerBuilderControls';
import EditableBurger from '../components/EditableBurger';
import useSummary from '../hooks/useSummary';

const BurgerBuilder = () => {
  const [ingredients, setIngredients] = useState({
    tomatos: 0,
    cheese: 0,
    patty: 0,
    pickles: 0,
  });

  const [isVeggie, setIsVeggie] = useState(true);

  const addIngredient = (key) => {
    setIngredients({
      ...ingredients,
      [key]: ingredients[key] + 1,
    });
  };

  const removeIngredient = (key) => {
    if (ingredients[key] > 0) {
      setIngredients({
        ...ingredients,
        [key]: ingredients[key] - 1,
      });
    }
  };

  const toggleVeggie = () => {
    setIsVeggie(!isVeggie);
  };

  // const [summary, setSummary] = useState('Your burger is empty 😢');

  // useEffect(() => {
  //   let totalAmount = 0;
  //   Object.values(ingredients).forEach((amount) => {
  //     totalAmount += amount;
  //   });
  //   if (totalAmount > 0) {
  //     setSummary(`Your burger has ${totalAmount} ingredients 🤤`);
  //   } else {
  //     setSummary('Your burger is empty 😢');
  //   }
  // }, [ingredients]);

  // const [summary] = useSummary(ingredients);

  return (
    <>
      <img src={logo} className='App-logo' alt='logo' />
      <div style={styles.builderContainer}>
        <h1>Welcome to amp burgerz 👋</h1>
        {/*<p>{summary}</p>*/}
        <BurgerBuilderControls
          addIngredient={addIngredient}
          isVeggie={isVeggie}
          toggleVeggie={toggleVeggie}
        />
        <EditableBurger
          ingredients={ingredients}
          isVeggie={isVeggie}
          removeIngredient={removeIngredient}
        />
      </div>
    </>
  );
};

const styles = {
  burgerContainer: {
    paddingTop: 20,
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
  },
  builderContainer: {
    paddingTop: 20,
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
  },
};

export default BurgerBuilder;
