// amp-burger-vue/src/components/ingredients/Cheese.vue
<template>
  <div class="cheeseContainer" v-for="n in amount" :key="n">
    <div class="cheese" />
  </div>
</template>

<script>
export default {
  name: 'Cheese',
  props: {
    amount: {
      default: 0,
    },
  },
};
</script>

<style scoped>
.cheeseContainer {
  position: relative;
  padding-bottom: 5px;
}
.cheese {
  position: absolute;
  left: -120px;
  top: 0px;
  border-left: 120px solid transparent;
  border-right: 120px solid transparent;
  border-top: 30px solid #e6a91b;
}
</style>

// amp-burger-react/src/components/ingredients/Cheese.jsx
const Cheese = ({ amount }) => {
  // return (
  return Array.from({ length: amount }, (v, i) => (
    <div key={i} style={{ position: "relative", paddingBottom: 5 }}>
      <div
        style={{
          position: "absolute",
          left: -120,
          top: 0,
          borderLeft: "120px solid transparent",
          borderRight: "120px solid transparent",
          borderTop: "30px solid #E6A91B",
        }}
      />
    </div>
  ));
};

export default Cheese;
