// amp-burger-vue/src/components/ingredients/Tomatos.vue
<template>
  <div class="tomatoContainer" v-for="n in amount" :key="n">
    <div class="tomato" />
    <div class="tomato" />
  </div>
</template>

<script>
export default {
  name: 'Tomatos',
  props: {
    amount: {
      default: 0,
    },
  },
};
</script>

<style scoped>
.tomatoContainer {
  display: flex;
  flex-direction: row;
  gap: 10px;
}
.tomato {
  width: 100px;
  height: 10px;
  background-color: #e7574a;
}
</style>

// amp-burger-react/src/components/ingredients/Tomatos.jsx
const Tomatos = ({ amount }) => {
  return Array.from({ length: amount }, (v, i) => (
    <div style={styles.container} key={i}>
      <div style={styles.tomato} />
      <div style={styles.tomato} />
    </div>
  ));
};

const styles = {
  container: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
  },
  tomato: {
    width: 100,
    height: 10,
    backgroundColor: '#E7574A',
  },
};

export default Tomatos;
