// amp-burger-react/src/components/BurgerBuilderControls.jsx
import Button from './Button';

const BurgerBuilderControls = ({ addIngredient, isVeggie, toggleVeggie }) => {
  return (
    <div style={styles.container}>
      <Button title='Add Tomatos 🍅' onClick={() => addIngredient('tomatos')} />
      <Button title='Add Patty 🍔' onClick={() => addIngredient('patty')} />
      <Button title='Add Cheese 🧀' onClick={() => addIngredient('cheese')} />
      <Button title='Add Pickles 🥒' onClick={() => addIngredient('pickles')} />
      <div style={styles.toggles}>
        <div>
          <input
            id='veggie'
            type='radio'
            checked={isVeggie}
            onChange={toggleVeggie}
          />
          <label htmlFor='veggie' style={{ paddingRight: 10, fontSize: 20 }}>
            Veggie 🥬
          </label>
        </div>
        <div>
          <input
            id='beef'
            type='radio'
            checked={!isVeggie}
            onChange={toggleVeggie}
          />
          <label htmlFor='beef' style={{ paddingRight: 10, fontSize: 20 }}>
            Beef 🍖
          </label>
        </div>
      </div>
    </div>
  );
};

const styles = {
  container: {
    width: 400,
    display: 'flex',
    flexFlow: 'row wrap',
    justifyContent: 'center',
    gap: 5,
  },
  toggles: {
    paddingTop: 10,
  },
};

export default BurgerBuilderControls;

// amp-burger-vue/src/components/BurgerBuilderControls.vue
<template>
  <div class="controlsContainer">
    <Button title="Add Tomatos 🍅" @onClick="addIngredient('tomatos')" />
    <Button title="Add Patty 🍔" @onClick="addIngredient('patty')" />
    <Button title="Add Cheese 🧀" @onClick="addIngredient('cheese')" />
    <Button title="Add Pickles 🥒" @onClick="addIngredient('pickles')" />
    <div class="toggles">
      <div>
        <input
          id="veggie"
          type="radio"
          value="true"
          :checked="isVeggie"
          @change="$emit('toggleVeggie')"
        />
        <label htmlFor="veggie" class="toggleLabel">Veggie 🥬</label>
      </div>
      <div>
        <input
          id="beef"
          type="radio"
          value="false"
          :checked="!isVeggie"
          @change="$emit('toggleVeggie')"
        />
        <label htmlFor="beef" class="toggleLabel">Beef 🍖</label>
      </div>
    </div>
  </div>
</template>

<script>
import Button from './Button.vue';

export default {
  name: 'BurgerBuilderControls',
  components: {
    Button,
  },
  props: {
    isVeggie: {
      type: Boolean,
      default: true,
    },
  },
  methods: {
    addIngredient(key) {
      this.$emit('addIngredient', key);
    },
  },
};
</script>

<style scoped>
.controlsContainer {
  width: 400px;
  display: flex;
  flex-flow: row wrap;
  justify-content: center;
  gap: 5px;
}
.toggles {
  padding-top: 10px;
}
.toggleLabel {
  padding-right: 10px;
  font-size: 20px;
}
</style>
