// amp-burger-react/src/components/EditableBurger.jsx
import BunBottom from "./ingredients/BunBottom";
import BunTop from "./ingredients/BunTop";
import Cheese from "./ingredients/Cheese";
import Patty from "./ingredients/Patty";
import Salad from "./ingredients/Salad";
import Tomatos from "./ingredients/Tomatos";
import Pickles from "./ingredients/Pickles";

const EditableBurger = ({ ingredients, isVeggie, removeIngredient }) => {
  return (
    <div style={styles.burgerContainer}>
      <BunTop />
      <Tomatos amount={ingredients.tomatos} />
      <Salad />
      <Cheese amount={ingredients.cheese} />
      <Patty
        isVeggie={isVeggie}
        amount={ingredients.patty}
        onClick={() => removeIngredient("patty")}
      />
      <Pickles amount={ingredients.pickles} />
      <BunBottom />
    </div>
  );
};

const styles = {
  burgerContainer: {
    paddingTop: 20,
    width: "100%",
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    paddingBottom: 200,
  },
};

export default EditableBurger;

// amp-burger-vue/src/components/EditableBurger.vue
<template>
  <div class="burgerContainer">
    <BunTop />
    <Tomatos :amount="ingredients.tomatos" />
    <Salad />
    <Cheese :amount="ingredients.cheese" />
    <Patty
      :amount="ingredients.patty"
      :isVeggie="isVeggie"
      @onClick="$emit('removeIngredient', 'patty')"
    />
    <Pickles :amount="ingredients.pickles" />
    <BunBottom />
  </div>
</template>

<script>
import BunTop from './ingredients/BunTop.vue';
import Tomatos from './ingredients/Tomatos.vue';
import Salad from './ingredients/Salad.vue';
import Cheese from './ingredients/Cheese.vue';
import Patty from './ingredients/Patty.vue';
import Pickles from './ingredients/Pickles.vue';
import BunBottom from './ingredients/BunBottom.vue';

export default {
  name: 'EditableBurger',
  components: {
    BunTop,
    Tomatos,
    Salad,
    Cheese,
    Patty,
    Pickles,
    BunBottom,
  },
  props: {
    ingredients: Object,
    isVeggie: Boolean,
  },
};
</script>

<style scoped>
.burgerContainer {
  padding-top: 20px;
  width: '100%';
  display: flex;
  align-items: center;
  flex-direction: column;
}
</style>
