// amp-burger-react/src/components/SimpleBurger.jsx
import BunBottom from './ingredients/BunBottom';
import BunTop from './ingredients/BunTop';
import Cheese from './ingredients/Cheese';
import Patty from './ingredients/Patty';
import Pickles from './ingredients/Pickles';
import Salad from './ingredients/Salad';
import Tomatos from './ingredients/Tomatos';

const SimpleBurger = () => {
  return (
    <div style={styles.burgerContainer}>
      <BunTop />
      <Tomatos amount={1} />
      <Salad />
      <Cheese amount={1} />
      <Patty amount={1} />
      <Pickles amount={1} />
      <BunBottom />
    </div>
  );
};

const styles = {
  burgerContainer: {
    paddingTop: 20,
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
  },
};

export default SimpleBurger;

// amp-burger-vue/src/components/SimpleBurger.vue
<template>
  <div class="burgerContainer">
    <BunTop />
    <Tomatos amount="1" />
    <Salad />
    <Cheese amount="1" />
    <Patty amount="1" />
    <Pickles amount="1" />
    <BunBottom />
  </div>
</template>

<script>
import BunTop from './ingredients/BunTop.vue';
import Tomatos from './ingredients/Tomatos.vue';
import Salad from './ingredients/Salad.vue';
import Cheese from './ingredients/Cheese.vue';
import Patty from './ingredients/Patty.vue';
import Pickles from './ingredients/Pickles.vue';
import BunBottom from './ingredients/BunBottom.vue';

export default {
  name: 'SimpleBurger',
  components: {
    BunTop,
    Tomatos,
    Salad,
    Cheese,
    Patty,
    Pickles,
    BunBottom,
  },
};
</script>

<style scoped>
.burgerContainer {
  padding-top: 20px;
  width: '100%';
  display: flex;
  align-items: center;
  flex-direction: column;
}
</style>
