// amp-burger-react/src/containers/BurgerBuilderSimple.jsx
import logo from './../logo.svg';

import SimpleBurger from '../components/SimpleBurger';

const BurgerBuilderSimple = () => {
  return (
    <>
      <img src={logo} className='App-logo' alt='logo' />

      <div style={styles.container}>
        <h1>Welcome to amp burgerz 👋</h1>
        <SimpleBurger />
      </div>
    </>
  );
};

const styles = {
  container: {
    paddingTop: 30,
    textAlign: 'center',
  },
};

export default BurgerBuilderSimple;

// amp-burger-vue/src/containers/BurgerBuilderSimple.vue
<template>
  <div class="container">
    <h1>Welcome to amp burgerz 👋</h1>
    <SimpleBurger />
  </div>
</template>

<script>
import SimpleBurger from '../components/SimpleBurger.vue';

export default {
  name: 'BurgerBuilderSimple',
  components: {
    SimpleBurger,
  },
};
</script>

<style scoped>
.container {
  padding-top: 30px;
  text-align: 'center';
}
</style>
