// amp-burger-react/src/containers/BurgerBuilderIterative.jsx
import logo from './../logo.svg';
import { useState } from 'react';
import BurgerBuilderControls from '../components/BurgerBuilderControls';
import IterativeBurger from '../components/IterativeBurger';

const BurgerBuilderIterative = () => {
  const [ingredients, setIngredients] = useState([]);

  const [isVeggie, setIsVeggie] = useState(true);

  const addIngredient = (key) => {
    setIngredients([{ type: key, amount: 1 }, ...ingredients]);
  };

  const toggleVeggie = () => {
    setIsVeggie(!isVeggie);
  };

  return (
    <>
      <img src={logo} className='App-logo' alt='logo' />
      <div style={styles.builderContainer}>
        <h1>Welcome to amp burgerz 👋</h1>
        <BurgerBuilderControls
          addIngredient={addIngredient}
          isVeggie={isVeggie}
          toggleVeggie={toggleVeggie}
        />
      </div>
      <IterativeBurger ingredients={ingredients} isVeggie={isVeggie} />
    </>
  );
};

const styles = {
  builderContainer: {
    paddingTop: 20,
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    gap: 10,
  },
};

export default BurgerBuilderIterative;

// amp-burger-vue/src/containers/BurgerBuilderIterative.vue
<template>
  <div class="container">
    <h1>Welcome to amp burgerz 👋</h1>
    <BurgerBuilderControls
      :isVeggie="isVeggie"
      @toggleVeggie="toggleVeggie"
      @addIngredient="addIngredient"
    />

    <IterativeBurger :isVeggie="isVeggie" :ingredients="ingredients" />
  </div>
</template>

<script>
import BurgerBuilderControls from '../components/BurgerBuilderControls.vue';
import IterativeBurger from '../components/IterativeBurger.vue';

export default {
  name: 'BurgerBuilderIterative',
  components: {
    BurgerBuilderControls,
    IterativeBurger,
  },
  data() {
    return {
      isVeggie: true,
      ingredients: [],
    };
  },
  methods: {
    toggleVeggie() {
      this.isVeggie = !this.isVeggie;
    },
    addIngredient(key) {
      this.ingredients = [{ type: key, amount: 1 }, ...this.ingredients];
    },
  },
};
</script>

<style scoped>
.container {
  padding-top: 20px;
  width: 100%;
  display: flex;
  align-items: center;
  flex-direction: column;
}
</style>
