// amp-burger-vue/src/components/Button.vue
<template>
  <button class="button" @click="$emit('onClick')">{{ title }}</button>
</template>

<script>
export default {
  name: 'Button',
  components: {},
  props: {
    title: String,
  },
};
</script>

<style scoped>
.button {
  width: 180px;
  height: 50px;
  font-size: 18px;
  background-color: #98d7d6;
  border-radius: 7px;
}
</style>

// amp-burger-react/src/components/Button.jsx
const Button = ({ title, onClick }) => {
  return (
    <button
      style={{
        width: 180,
        height: 50,
        fontSize: 18,
        backgroundColor: "#98d7d6",
        borderRadius: 7,
      }}
      onClick={onClick}
    >
      {title}
    </button>
  );
};

export default Button;
