// amp-burger-vue/src/components/IterativeBurger.vue
<template>
  <div class="burgerContainer">
    <BunTop />
    <Salad />
    <Ingredient
      v-for="i in ingredients"
      :key="i"
      :type="i.type"
      :amount="i.amount"
      :isVeggie="isVeggie"
    />
    <BunBottom />
  </div>
</template>

<script>
import Ingredient from './Ingredient.vue';
import BunTop from './ingredients/BunTop.vue';
import Salad from './ingredients/Salad.vue';
import BunBottom from './ingredients/BunBottom.vue';

export default {
  name: 'IterativeBurger',
  components: {
    Ingredient,
    BunTop,
    Salad,
    BunBottom,
  },
  props: {
    ingredients: Array,
    isVeggie: Boolean,
  },
};
</script>

<style scoped>
.burgerContainer {
  padding-top: 20px;
  width: '100%';
  display: flex;
  align-items: center;
  flex-direction: column;
}
</style>

// amp-burger-react/src/components/IterativeBurger.jsx
import BunBottom from "./ingredients/BunBottom";
import BunTop from "./ingredients/BunTop";
import Salad from "./ingredients/Salad";
import Ingredient from "./Ingredient";

const IterativeBurger = ({ ingredients, isVeggie }) => {
  return (
    <div style={styles.burgerContainer}>
      <BunTop />
      <Salad />
      {ingredients.map((ingredient, i) => (
        <Ingredient
          key={i}
          type={ingredient.type}
          amount={ingredient.amount}
          isVeggie={isVeggie}
        />
      ))}
      <BunBottom />
    </div>
  );
};

const styles = {
  burgerContainer: {
    paddingTop: 20,
    width: "100%",
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    paddingBottom: 200,
  },
};
export default IterativeBurger;
